name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyInstaller
      - name: Bundle
        run: |
          python -m PyInstaller main.py --onefile -n VocaloidBankInstaller
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          # Artifact name
          name: VocaloidBankInstaller
          # Destination path
          path: dist/*.exe # optional
